# Generated by Django 4.2.11 on 2024-04-15 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('refresh', models.BooleanField(default=True)),
                ('data', models.JSONField(default=dict)),
                ('records_length', models.CharField(max_length=500)),
                ('api_url', models.CharField(default='', max_length=500)),
                ('api_isactive', models.BooleanField(default=False)),
                ('api_password', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sheet',
            },
        ),
    ]
