# Generated by Django 4.2.11 on 2024-04-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('refresh', models.BooleanField(default=True)),
                ('data', models.JSONField(default=dict)),
                ('records_length', models.CharField(max_length=500)),
                ('loadImages', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'excel_database',
            },
        ),
    ]
