# Generated by Django 4.2.11 on 2024-04-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data_engine', '0004_alter_excel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='api_password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
