# Generated by Django 4.2.11 on 2024-04-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data_engine', '0006_excel_api_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='api_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
